### PR TITLE
added ability to use equals from the cli

### PR DESCRIPTION
**Pull request by jhughes1153**

### CODE REVIEW

**Comment by PeterlitsZo** [comment]
Hi, jhughes,
Do you think `--flag="some thing"` is a better idea?
Peterlits Zo

**Comment by jhughes1153** [comment]
> Hi, jhughes,
> Do you think `--flag="some thing"` is a better idea? (If it is a `String` flag)
> Oh! what will happen if I access it with command `--string-flag "this"`? Will the value of that argument be `"this"` but not `this`? It is really?
> Peterlits Zo



> Hi, jhughes,
> Do you think `--flag="some thing"` is a better idea? (If it is a `String` flag)
> Oh! what will happen if I access it with command `--string-flag "this"`? Will the value of that argument be `"this"` but not `this`? It is really?
> Peterlits Zo

I believe this works with --flag="some string with spaces" and if you want to to have the string in the program be "some string with spaces" you pass in --flag="\"some string with spaces"\". Usually if you need to pass in some value from the cli with spaces you would use quotes, thats a very common linux practice.

**Comment by akamensky** [comment]
@jhughes1153 many thanks, that is a great addition to this library to make it more compatible with CLI standards.

Can you please add tests covering cases when equals used for types other than string (your tests currently only cover string arguments.

For simplicity you can modify existing tests for other types by adding additional validations there.

**Comment by PeterlitsZo** [comment]
Hi, @jhughes1153 ,
I get it! I do know less than I think...
Thanks for your reply.

**Comment by jhughes1153** [comment]
> @jhughes1153 many thanks, that is a great addition to this library to make it more compatible with CLI standards.
> 
> Can you please add tests covering cases when equals used for types other than string (your tests currently only cover string arguments.
> 
> For simplicity you can modify existing tests for other types by adding additional validations there.

Yeah, I added a few more types but not all, do you want full coverage for every type or are the types that I added fine?

**Comment by akamensky** [comment]
Thanks. LGTM.

**Pull request merged**
