### PR TITLE
Flag counter usage fix

### LINKED ISSUE #96: FlagCounter display unexpectedly
Given a `FlagCounter` arg definition as following

```go
verboseCounter = parser.FlagCounter("v", "verbose", &argparse.Options{
  Required: false,
  Validate: nil,
  Help:     "",
  Default:  0,
})
```

the help message displays it in the same style as an `Int` arg.

```
 [-v|--verbose <integer>]
```

however, it can not be used in the same way as an `Int` arg

```
-v 1
-v 2
-v 3
```

instead it should be used in the flag way.

```
-v
-vv
-vvv
```

### PR DESCRIPTION
**Pull request by Alec-Bakholdin**
Resolves #96 
Removed <integer> from FlagCounter usage string and added example for FlagCounter

### CODE REVIEW

**Comment by Alec-Bakholdin** [comment]
Same thing as in PR #99, Travis CI failing because it can't find goveralls even though it was installed earlier

**Review by akamensky — APPROVED** [review]
LGTM

**Comment by akamensky** [comment]
Same comment as in #99, waiting for coveralls to recover their service so can merge the fix for build.

**Comment by akamensky** [comment]
@Alec-Bakholdin Could you please rebase the changes onto master to fix the coverage reporting?

**Pull request merged**
